### ISSUE TITLE
nimbleparse example in book fails

### ISSUE THREAD

**Issue by josepablocam** [softdevteam/grammars#13]
I'm trying out the basic `nimbleparse` example shown in the book but am getting an error around the lexer file. It looks like I have nimbparse built (and I add `target/release` to `PATH`). 

```
$ git clone git@github.com:softdevteam/grammars.git
$ pushd grammars; git rev-parse HEAD
b51fb08f25bbfcc8d0ae637599ec446bc63efdd1
$ popd
$ cat bad.java
class SyntaxError {
    int x y;
}
$ nimbleparse grammars/java7/java.l grammars/java7/java.y bad.java
grammars/java7/java.l: [Error] Invalid start state at line 71 column 1
```

Looks like these are due to `<` leading characters in the regular expressions (same at a couple of other lines). If I add a `\` to each `<` character, then it seems to work ok. Is this expected? The lexer section mentions this, but the `nimbleparse` example doesn't so was wondering if there is an option I should use to avoid this issue.

**Comment by ltratt** [comment]
Oops, yes, the `grammars` repository needs an update for lrlex's new start state facility. Thanks for pointing this out -- fixed in https://github.com/softdevteam/grammars/pull/14.

**Comment by josepablocam** [comment]
Thanks for the clarification/fix @ltratt . I'll go ahead and close this issue now since this addresses it.
